{% set name = "qrcode" %}
{% set version = "7.3" %}
{% set sha256 = "d72861b65e26b611609f0547f0febe58aed8ae229d6bf4e675834f40742915b3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - qr = qrcode.console_scripts:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - setuptools
    - six
    - colorama

test:
  imports:
    - qrcode
    - qrcode.image
    - qrcode.tests
  commands:
    - qr --help

about:
  home: https://github.com/lincolnloop/python-qrcode
  license: BSD-3-Clause
  license_file: LICENSE
  summary: QR Code image generator
